name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout         

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Docker image
      run: |
        docker build -t test .

    - name: Tag Docker image
      run: docker tag test korede01/cloudhight:latest    

    - name: push to docker hub 
      run:  docker push korede01/cloudhight
  
  Deploy-to-ASG-prod:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: create new lauch template 
        run: |
          echo "${{ secrets.TEMPLATE }}" >> userdate.sh

        -  

      - name: Deploy Launch Template
        env:
          LAUNCH_TEMPLATE_NAME: ${{ secrets.LAUNCH_TEMPLATE_NAME }}
        run: |
          aws ec2 create-launch-template --launch-template-name "${LAUNCH_TEMPLATE_NAME}" --version-description "Initial version" --tag-specifications 'ResourceType=launch-template,Tags=[{Key=Name,Value="${LAUNCH_TEMPLATE_NAME}"}]' --user-data file://userdata.sh